[package]
name = "fulf"
edition = "2018"
version = "0.1.0"
authors = ["ImmConCon <somewhat.fluffy@gmail.com>"]
license = "MIT"
publish = false

[dependencies]
memchr = "^2.3.3"
ignore = "^0.4.14"
flume = "^0.7.1"
inlinable_string = "^0.1.11"
